version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: payroll
      MYSQL_ROOT_PASSWORD: password123
    command: mysqld --default-authentication-plugin=caching_sha2_password
    volumes:
      - ./docker-db/mysql-data:/var/lib/mysql:rw
